name: MatrixOne ALL CI

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: [ main,'[0-9]+.[0-9]+*',panic-2-main ]

concurrency: 
  group: ${{ github.event.pull_request.head.repo.full_name}}/${{ github.event.pull_request.head.ref }}/${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-pr-valid:
    runs-on: ubuntu-latest
    name: CHECK PR VALID
    outputs:
      pr_valid: ${{ steps.check_pr_valid.outputs.pull_valid }}
    steps:
      - uses: Rosyrain/CI/actions/pulls-content-check@fix-CI-ut-painc-test
        id: check_pr_valid
        with:
          github_token: ${{ secrets.TOKEN_ACTION }}
          title_for_find_issue: "Which issue(s) this PR fixes:"
          title_for_find_content: "What this PR does / why we need it:"

  matrixone-ci:
    name: Matrixone CI
    needs: 
      - check-pr-valid
    if: ${{ needs.check-pr-valid.outputs.pr_valid == 'true' }}
    uses: Rosyrain/CI/.github/workflows/ci.yaml@fix-CI-ut-painc-test
    secrets:
      S3ENDPOINT: ${{ secrets.S3ENDPOINT }}
      S3REGION: ${{ secrets.S3REGION }}
      S3APIKEY: ${{ secrets.S3APIKEY }}
      S3APISECRET: ${{ secrets.S3APISECRET }}
      S3BUCKET: ${{ secrets.S3BUCKET }}
  
  matrixone-upgrade-ci:
    name: Matrixone Upgrade CI
    needs: 
      - check-pr-valid
    if: ${{ needs.check-pr-valid.outputs.pr_valid == 'true' }}
    uses: Rosyrain/CI/.github/workflows/e2e-upgrade.yaml@fix-CI-ut-painc-test

  matrixone-compose-ci:
    name: Matrixone Compose CI
    needs: 
      - check-pr-valid
    if: ${{ needs.check-pr-valid.outputs.pr_valid == 'true' }}
    uses: Rosyrain/CI/.github/workflows/e2e-compose.yaml@fix-CI-ut-painc-test

  matrixone-standalone-ci:
    name: Matrixone Standlone CI
    needs: 
      - check-pr-valid
    if: ${{ needs.check-pr-valid.outputs.pr_valid == 'true' }}
    uses: Rosyrain/CI/.github/workflows/e2e-standalone.yaml@fix-CI-ut-painc-test

  matrixone-utils-ci:
    name: Matrixone Utils CI
    needs: 
      - check-pr-valid
    if: ${{ needs.check-pr-valid.outputs.pr_valid == 'true' }}
    uses: Rosyrain/CI/.github/workflows/utils.yaml@fix-CI-ut-painc-test
    secrets:
      TOKEN_ACTION: ${{ secrets.TOKEN_ACTION }}
      TEST_S3FS_ALIYUN: ${{ secrets.TEST_S3FS_ALIYUN }}
      TEST_S3FS_QCLOUD: ${{ secrets.TEST_S3FS_QCLOUD }}
      DOCU_GROUP_HOOK: ${{ secrets.DOCU_GROUP_HOOK }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
